### ISSUE TITLE
Bootstrap script doesnt work on linux

### ISSUE THREAD

**Issue by trondhindenes** [cake-build/frosting#49] opened 2017-12-21 16:28 UTC
Getting multiple errors when running the bootstrap script on a Linux host with .Net core / Powershell core installed:
```
/bin/mkdir: invalid option -- 'F'
Try '/bin/mkdir --help' for more information.
Architecture not supported. If you think this is a bug, please report it at https://github.com/dotnet/cli/issues
At /home/trond/Documents/projects/frosting/.dotnet\dotnet-install.ps1:139 char:19
+ ...   default { throw "Architecture not supported. If you think this is a ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Architecture no...tnet/cli/issues:String) [], RuntimeException
+ FullyQualifiedErrorId : Architecture not supported. If you think this is a bug, please report it at https://github.com/dotnet/cli/issues
```

What are the plans regarding support for linux-based operating systems?

**Comment by jjschlesinger** [comment] 2018-01-03 00:16
I am working on a bash version. I will do a pull request when it is ready to go.

**Comment by trondhindenes** [comment] 2018-01-04 12:53
Powershell on linux is fine aswell, but it should be compatible with Powershell.Core

**Comment by devlead** [comment] 2018-01-04 13:10
@trondhindenes the error is actually coming from ".dotnet\dotnet-install.ps1" which is a script provided Microsoft part of the .NET CLI repo, a possible solution could be to use the bash obtain script on Linux.

But perhaps correct way would be to raise an issue at https://github.com/dotnet/cli/issues as part is a bit out of scope for Cake Frosting.
So PowerShell.Core support could be added to https://github.com/dotnet/cli/blob/master/scripts/obtain/dotnet-install.ps1

**Comment by qayshp** [comment] 2018-03-16 07:57
Just ran into the same issue on macOS. I understand that the root cause is inside dotnet and commented on https://github.com/dotnet/cli/issues/8278 . Since it's been a few weeks since the last comments here, I'm just looking for suggestions right now.

**Comment by devlead** [comment] 2018-03-16 08:18
This is an example what I've done for my PowerShell core compatible bootstrappers:
https://github.com/cake-contrib/Cake.Kudu.Client/blob/develop/build.ps1

It's cheating... As I'm invoking the bash script on posix, but then again it works😎

**Comment by jjschlesinger** [comment] 2018-03-16 14:23
This is how I'm bootstrapping dotnet core in bash...

```###########################################################################
# INSTALL .NET CORE CLI
###########################################################################
export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
export DOTNET_CLI_TELEMETRY_OPTOUT=1

if [ -z $CAKE_USE_DOTNET_ON_PATH ]; then
    echo "Installing .NET CLI..."
    if [ ! -d "$SCRIPT_DIR/.dotnet" ]; then
    mkdir "$SCRIPT_DIR/.dotnet"
    fi

    if [ ! -e "$SCRIPT_DIR/.dotnet/dotnet" ]; then
    curl -Lsfo "$SCRIPT_DIR/.dotnet/dotnet-install.sh" https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh
    sudo bash "$SCRIPT_DIR/.dotnet/dotnet-install.sh" --version $DOTNET_SDK_VERSION --install-dir .dotnet --no-path
    else
        echo ".Net CLI installed."
    fi

    export PATH="$SCRIPT_DIR/.dotnet":$PATH
else
    echo "Using dotnet on current path..."
fi```

**Comment by gep13** [comment] 2020-07-01 20:14
@jjschlesinger @qayshp @trondhindenes I am going to go ahead and close this issue, as I don't believe it is still a problem.

If you are still having issues, feel free to reach out.

**Closed by gep13** 2020-07-01 20:14 UTC
