### ISSUE TITLE
Add support for Ansi console.

### ISSUE THREAD

**Issue by devlead** [cake-build/frosting#70] opened 2020-06-26 10:47 UTC
Cake 0.38.0 added support for ANSI console, but it's internal in Cake.Core so not avail to frosting default console.

**Comment by gep13** [comment] 2020-06-26 12:06
This is a duplicate of this issue: 

https://github.com/cake-build/frosting/issues/10

So going to go ahead and close this out.

**Closed by gep13** 2020-06-26 12:06 UTC
Labels: duplicate
